jobs:
  - job: Build
    variables:
      - template: ../variables/globals.yml
    pool:
      vmImage: windows-2019
    steps:
      - template: ../steps/arrange-artifacts.yml
        parameters:
          Artifacts: ${{ parameters.Artifacts }}